In [65]:
import numpy as np

# DataTypes and Attributes

In [66]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [67]:
type(a1)

numpy.ndarray

In [68]:
a2 = np.array([[1.2,5.3,2],[5.6,7,6.9]])
a3 = np.array([[[ 1, 2, 3],
                [ 4, 5, 6],
                [ 7, 8, 9]],
               
               [[ 10, 11, 12],
                [ 13, 14, 15],
                [ 16, 17, 18]]])

In [69]:
a2

array([[1.2, 5.3, 2. ],
       [5.6, 7. , 6.9]])

In [70]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [71]:
a1.shape

(3,)

In [72]:
a2.shape

(2, 3)

In [73]:
a3.shape

(2, 3, 3)

In [74]:
a1.ndim

1

In [75]:
a2.ndim

2

In [76]:
a3.ndim

3

In [77]:
a1.dtype , a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [78]:
a1.size ,a2.size,a3.size

(3, 6, 18)

In [79]:
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [80]:
 # Create a DataFrame from NumPy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.2  5.3  2.0
1  5.6  7.0  6.9

In [81]:
df.columns = ["c1","c2","c3"]

In [82]:
df.columns

Index(['c1', 'c2', 'c3'], dtype='object')

In [83]:
df

c1   c2   c3
0  1.2  5.3  2.0
1  5.6  7.0  6.9

## Creating Arrays

In [84]:
sample_array = np.array(range(1,4))
sample_array

array([1, 2, 3])

In [85]:
sample_array.dtype

dtype('int32')

In [86]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [87]:
ones.dtype

dtype('float64')

In [88]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
range_array = np.arange(0,20,2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
random_array = np.random.randint(0 , 15 ,size = (2,5,2))
random_array

array([[[ 0,  2],
        [ 1,  9],
        [12,  1],
        [14,  0],
        [ 7,  6]],

       [[12, 12],
        [ 9,  6],
        [ 3,  9],
        [ 3, 11],
        [11, 10]]])

In [91]:
random_array.shape

(2, 5, 2)

In [92]:
random_array.ndim

3

In [93]:
random_array.size

20

In [94]:
len(random_array)

2

In [95]:
random_array.dtype

dtype('int32')

In [96]:
r2 = random_array.astype(str)
r2

array([[['0', '2'],
        ['1', '9'],
        ['12', '1'],
        ['14', '0'],
        ['7', '6']],

       [['12', '12'],
        ['9', '6'],
        ['3', '9'],
        ['3', '11'],
        ['11', '10']]], dtype='<U11')

In [97]:
random_array.dtype

dtype('int32')

In [98]:
random_array_2 = np.random.random((2,3))

In [99]:
random_array_2.dtype

dtype('float64')

In [100]:
random_array_2.shape

(2, 3)

In [101]:
random_array_2.ndim

2

In [102]:
random_array_3 = np.random.rand(5,3)

In [103]:
np.random.uniform(0.0,20.0, size = (5,2))

array([[16.68975156, 10.15888987],
       [ 5.81925779,  2.58905279],
       [ 8.3693993 ,  0.98748593],
       [ 6.00288407, 17.29825076],
       [10.39448899,  2.54025782]])

In [104]:
random_array_3

array([[0.73478493, 0.7534509 , 0.52954037],
       [0.33769955, 0.44548373, 0.03576527],
       [0.2155956 , 0.099903  , 0.99220702],
       [0.35245482, 0.84934936, 0.07482481],
       [0.68331934, 0.55363888, 0.61705263]])

In [106]:
# Pseudo random numbers
np.random.seed()