In [1]:
import numpy as np

# DataTypes and Attributes

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1.2,5.3,2],[5.6,7,6.9]])
a3 = np.array([[[ 1, 2, 3],
                [ 4, 5, 6],
                [ 7, 8, 9]],
               
               [[ 10, 11, 12],
                [ 13, 14, 15],
                [ 16, 17, 18]]])

In [5]:
a2

array([[1.2, 5.3, 2. ],
       [5.6, 7. , 6.9]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim

1

In [11]:
a2.ndim

2

In [12]:
a3.ndim

3

In [13]:
a1.dtype , a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size ,a2.size,a3.size

(3, 6, 18)

In [15]:
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
 # Create a DataFrame from NumPy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.2  5.3  2.0
1  5.6  7.0  6.9

In [17]:
df.columns = ["c1","c2","c3"]

In [18]:
df.columns

Index(['c1', 'c2', 'c3'], dtype='object')

In [19]:
df

c1   c2   c3
0  1.2  5.3  2.0
1  5.6  7.0  6.9

## Creating Arrays

In [20]:
sample_array = np.array(range(1,4))
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int32')

In [22]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0,20,2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
random_array = np.random.randint(0 , 15 ,size = (2,5,2))
random_array

array([[[ 3, 12],
        [ 7, 13],
        [ 9, 11],
        [ 2, 12],
        [11,  5]],

       [[ 5,  0],
        [ 0,  7],
        [14,  3],
        [ 6,  4],
        [ 6, 11]]])

In [27]:
random_array.shape

(2, 5, 2)

In [28]:
random_array.ndim

3

In [29]:
random_array.size

20

In [30]:
len(random_array)

2

In [31]:
random_array.dtype

dtype('int32')

In [32]:
r2 = random_array.astype(str)
r2

array([[['3', '12'],
        ['7', '13'],
        ['9', '11'],
        ['2', '12'],
        ['11', '5']],

       [['5', '0'],
        ['0', '7'],
        ['14', '3'],
        ['6', '4'],
        ['6', '11']]], dtype='<U11')

In [33]:
random_array.dtype

dtype('int32')

In [34]:
random_array_2 = np.random.random((2,3))

In [35]:
random_array_2.dtype

dtype('float64')

In [36]:
random_array_2.shape

(2, 3)

In [37]:
random_array_2.ndim

2

In [38]:
random_array_3 = np.random.rand(5,3)

In [39]:
np.random.uniform(0.0,20.0, size = (5,2))

array([[16.88406287,  6.11450574],
       [ 7.69010431,  9.05744623],
       [ 8.08386236, 17.83551314],
       [15.39603337, 18.40159881],
       [15.14070012, 11.0751739 ]])

In [40]:
random_array_3

array([[0.81319651, 0.3531765 , 0.83017356],
       [0.66770576, 0.69766045, 0.02321451],
       [0.2223013 , 0.6976335 , 0.88805886],
       [0.67290581, 0.8375874 , 0.51956672],
       [0.11920501, 0.33479246, 0.43266841]])

In [49]:
# Pseudo random numbers
#np.random.seed(seed=0)
random_array_4 = np.random.randint(5, size=(2,3))
random_array_4

array([[3, 2, 4],
       [0, 0, 4]])

In [46]:
random_array_4.shape , random_array_4.ndim , random_array_4.dtype , len(random_array_4) , random_array_4.size

((2, 3), 2, dtype('int32'), 2, 6)

In [55]:
#np.random.seed(seed=69)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.16291775, 0.55515857, 0.12678515],
       [0.94573522, 0.98261237, 0.30144613],
       [0.76962557, 0.31195002, 0.9781755 ],
       [0.28127815, 0.67381034, 0.43307378],
       [0.40467841, 0.58101849, 0.59158113]])

# Viewing Arrays and Matrices