In [2]:
import numpy as np

# DataTypes and Attributes

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1.2,5.3,2],[5.6,7,6.9]])
a3 = np.array([[[ 1, 2, 3],
                [ 4, 5, 6],
                [ 7, 8, 9]],
               
               [[ 10, 11, 12],
                [ 13, 14, 15],
                [ 16, 17, 18]]])

In [6]:
a2

array([[1.2, 5.3, 2. ],
       [5.6, 7. , 6.9]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim

1

In [12]:
a2.ndim

2

In [13]:
a3.ndim

3

In [14]:
a1.dtype , a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
a1.size ,a2.size,a3.size

(3, 6, 18)

In [16]:
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
 # Create a DataFrame from NumPy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.2  5.3  2.0
1  5.6  7.0  6.9

In [18]:
df.columns = ["c1","c2","c3"]

In [19]:
df.columns

Index(['c1', 'c2', 'c3'], dtype='object')

In [20]:
df

c1   c2   c3
0  1.2  5.3  2.0
1  5.6  7.0  6.9

## Creating Arrays

In [21]:
sample_array = np.array(range(1,4))
sample_array

array([1, 2, 3])

In [22]:
sample_array.dtype

dtype('int32')

In [23]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0,20,2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
random_array = np.random.randint(0 , 15 ,size = (2,5,2))
random_array

array([[[ 6,  9],
        [13,  3],
        [ 5, 13],
        [ 8, 12],
        [13, 10]],

       [[12, 13],
        [ 1,  7],
        [ 4,  2],
        [ 9,  1],
        [ 2,  6]]])

In [28]:
random_array.shape

(2, 5, 2)

In [29]:
random_array.ndim

3

In [30]:
random_array.size

20

In [31]:
len(random_array)

2

In [32]:
random_array.dtype

dtype('int32')

In [33]:
r2 = random_array.astype(str)
r2

array([[['6', '9'],
        ['13', '3'],
        ['5', '13'],
        ['8', '12'],
        ['13', '10']],

       [['12', '13'],
        ['1', '7'],
        ['4', '2'],
        ['9', '1'],
        ['2', '6']]], dtype='<U11')

In [34]:
random_array.dtype

dtype('int32')

In [35]:
random_array_2 = np.random.random((2,3))

In [36]:
random_array_2.dtype

dtype('float64')

In [37]:
random_array_2.shape

(2, 3)

In [38]:
random_array_2.ndim

2

In [39]:
random_array_3 = np.random.rand(5,3)

In [40]:
np.random.uniform(0.0,20.0, size = (5,2))

array([[17.27164625,  9.7538221 ],
       [18.34751806, 13.1306163 ],
       [12.20383975, 13.48037794],
       [11.53228458,  9.04440237],
       [15.17506001,  7.98802672]])

In [41]:
random_array_3

array([[0.65875337, 0.95080038, 0.69665835],
       [0.68856683, 0.20445579, 0.67468395],
       [0.14858726, 0.39639343, 0.66787687],
       [0.26875112, 0.19667506, 0.35548619],
       [0.39786067, 0.2918353 , 0.01599883]])

In [42]:
# Pseudo random numbers
#np.random.seed(seed=0)
random_array_4 = np.random.randint(5, size=(2,3))
random_array_4

array([[3, 3, 3],
       [1, 1, 2]])

In [43]:
random_array_4.shape , random_array_4.ndim , random_array_4.dtype , len(random_array_4) , random_array_4.size

((2, 3), 2, dtype('int32'), 2, 6)

In [44]:
#np.random.seed(seed=69)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.69409128, 0.86385734, 0.23316339],
       [0.63716779, 0.26292193, 0.70309272],
       [0.97964101, 0.44524097, 0.25677097],
       [0.12920586, 0.75994251, 0.91661213],
       [0.37203428, 0.94216661, 0.08300408]])

# Viewing Arrays and Matrices

In [45]:
np.unique(random_array_4)

array([1, 2, 3])

In [46]:
a1

array([1, 2, 3])

In [47]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
np.unique(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [49]:
a1[0]

1

In [50]:
a2[1]

array([5.6, 7. , 6.9])

In [51]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [53]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [54]:
a4 = np.random.randint(5.0 , size=(2,3,3,5),dtype=int)

In [55]:
a4

array([[[[0, 4, 2, 3, 4],
         [3, 0, 3, 0, 0],
         [4, 1, 3, 2, 3]],

        [[2, 1, 0, 2, 4],
         [0, 2, 2, 3, 3],
         [0, 2, 0, 1, 2]],

        [[0, 4, 0, 1, 1],
         [4, 3, 3, 3, 0],
         [1, 3, 4, 3, 4]]],


       [[[3, 0, 1, 3, 0],
         [0, 3, 2, 2, 0],
         [3, 3, 0, 0, 3]],

        [[1, 4, 4, 0, 0],
         [1, 0, 0, 1, 2],
         [0, 1, 3, 1, 0]],

        [[4, 2, 2, 2, 2],
         [4, 3, 0, 2, 2],
         [2, 4, 1, 1, 0]]]])

In [56]:
a4.shape,a4.ndim,a4.size,len(a4),type(a4)

((2, 3, 3, 5), 4, 90, 2, numpy.ndarray)

In [57]:
a4.sum()

162

In [58]:
# slice the 4 first elements in the array

a4[:,:,:,:1]

array([[[[0],
         [3],
         [4]],

        [[2],
         [0],
         [0]],

        [[0],
         [4],
         [1]]],


       [[[3],
         [0],
         [3]],

        [[1],
         [1],
         [0]],

        [[4],
         [4],
         [2]]]])

# Manipulating & Comparing Data

## Arithmetic 

In [59]:
a1

array([1, 2, 3])

In [60]:
ones = np.ones((5,3),dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [61]:
a1 + ones

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [62]:
a1 - ones

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [63]:
a1* ones

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [64]:
a1 * a2

array([[ 1.2, 10.6,  6. ],
       [ 5.6, 14. , 20.7]])

In [65]:
a1 / a2

array([[0.83333333, 0.37735849, 1.5       ],
       [0.17857143, 0.28571429, 0.43478261]])

In [66]:
np.dot(a2,a3)

array([[[ 36.4,  44.9,  53.4],
        [112.9, 121.4, 129.9]],

       [[ 81.9, 101.4, 120.9],
        [257.4, 276.9, 296.4]]])

In [67]:
a2 // a1

array([[1., 2., 0.],
       [5., 3., 2.]])

In [68]:
a2**2

array([[ 1.44, 28.09,  4.  ],
       [31.36, 49.  , 47.61]])

In [69]:
np.add(a1,ones)

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [70]:
a1%2

array([1, 0, 1], dtype=int32)

In [71]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [72]:
a1

array([1, 2, 3])

In [73]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [74]:
0.69314718**2

0.4804530131419524

In [75]:
0.69314718 * 0.69314718

0.4804530131419524

In [76]:
0.69314718 * 2

1.38629436

## Aggregation 
### Aggregation = performing the same operation on a number things

In [77]:
list = [1,2,3,1,5]
list

[1, 2, 3, 1, 5]

In [79]:
sum(list)

12

In [80]:
np.sum(a1),sum(a1)

(6, 6)

Use Python methods (``sum()``) on Python DataTypes and Use Numpy Methods on Numpy DataTypes

In [82]:
# Create a Massive Array

In [87]:
m_a = np.random.random(1000)
m_a

array([0.30622655, 0.20596124, 0.75662368, 0.7845449 , 0.42213031,
       0.3630281 , 0.83007237, 0.15833186, 0.0025247 , 0.90021145,
       0.04643024, 0.83881684, 0.14728916, 0.2807975 , 0.89129478,
       0.79232149, 0.91667386, 0.27160685, 0.42576878, 0.80940908,
       0.37331145, 0.54293616, 0.27743927, 0.81463811, 0.25299444,
       0.88197984, 0.34687508, 0.90014988, 0.14870483, 0.40966755,
       0.38843959, 0.45460889, 0.98815139, 0.67375382, 0.24505931,
       0.66441629, 0.94941205, 0.89438739, 0.47643757, 0.54326016,
       0.47177285, 0.8092186 , 0.14197763, 0.5994578 , 0.03142801,
       0.15620459, 0.49226611, 0.35785755, 0.96533376, 0.14192141,
       0.67818689, 0.07847619, 0.78451722, 0.9019412 , 0.16619536,
       0.04120434, 0.08100419, 0.5268654 , 0.31003582, 0.61138183,
       0.45644676, 0.5034254 , 0.49243579, 0.15488642, 0.47155368,
       0.46864643, 0.89009256, 0.36717979, 0.10195964, 0.46120575,
       0.73927749, 0.46438839, 0.3646511 , 0.68926583, 0.35212

In [88]:
m_a[:10]

array([0.30622655, 0.20596124, 0.75662368, 0.7845449 , 0.42213031,
       0.3630281 , 0.83007237, 0.15833186, 0.0025247 , 0.90021145])

In [89]:
sum(m_a)

498.6063903845335

In [90]:
%timeit sum(m_a) #how much it takes time to sum this big array Python Method
%timeit np.sum(m_a) #Numpy Method

65.1 µs ± 976 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
3.38 µs ± 19.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [91]:
a2

array([[1.2, 5.3, 2. ],
       [5.6, 7. , 6.9]])

In [93]:
np.mean(a2)

4.666666666666667

In [94]:
np.std(a2)

2.266911751455907

In [95]:
#Variance 
np.var(a2)

5.138888888888888

In [96]:

np.sqrt(np.var(a2))

2.266911751455907