In [1]:
import numpy as np

# DataTypes and Attributes

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1.2,5.3,2],[5.6,7,6.9]])
a3 = np.array([[[ 1, 2, 3],
                [ 4, 5, 6],
                [ 7, 8, 9]],
               
               [[ 10, 11, 12],
                [ 13, 14, 15],
                [ 16, 17, 18]]])

In [5]:
a2

array([[1.2, 5.3, 2. ],
       [5.6, 7. , 6.9]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim

1

In [11]:
a2.ndim

2

In [12]:
a3.ndim

3

In [13]:
a1.dtype , a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size ,a2.size,a3.size

(3, 6, 18)

In [15]:
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
 # Create a DataFrame from NumPy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.2  5.3  2.0
1  5.6  7.0  6.9

In [17]:
df.columns = ["c1","c2","c3"]

In [18]:
df.columns

Index(['c1', 'c2', 'c3'], dtype='object')

In [19]:
df

c1   c2   c3
0  1.2  5.3  2.0
1  5.6  7.0  6.9

## Creating Arrays

In [20]:
sample_array = np.array(range(1,4))
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int32')

In [22]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0,20,2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
random_array = np.random.randint(0 , 15 ,size = (2,5,2))
random_array

array([[[ 7,  0],
        [ 6,  1],
        [ 4,  6],
        [13,  5],
        [ 5, 14]],

       [[ 2,  5],
        [13,  0],
        [11, 13],
        [ 0,  9],
        [12,  5]]])

In [27]:
random_array.shape

(2, 5, 2)

In [28]:
random_array.ndim

3

In [29]:
random_array.size

20

In [30]:
len(random_array)

2

In [31]:
random_array.dtype

dtype('int32')

In [32]:
r2 = random_array.astype(str)
r2

array([[['7', '0'],
        ['6', '1'],
        ['4', '6'],
        ['13', '5'],
        ['5', '14']],

       [['2', '5'],
        ['13', '0'],
        ['11', '13'],
        ['0', '9'],
        ['12', '5']]], dtype='<U11')

In [33]:
random_array.dtype

dtype('int32')

In [34]:
random_array_2 = np.random.random((2,3))

In [35]:
random_array_2.dtype

dtype('float64')

In [36]:
random_array_2.shape

(2, 3)

In [37]:
random_array_2.ndim

2

In [38]:
random_array_3 = np.random.rand(5,3)

In [39]:
np.random.uniform(0.0,20.0, size = (5,2))

array([[16.10258012, 16.97615995],
       [13.05688025, 16.63461822],
       [ 3.07738961, 19.75672269],
       [14.8912473 ,  1.94372818],
       [14.82461167, 14.82130078]])

In [40]:
random_array_3

array([[0.10778342, 0.31470168, 0.84222268],
       [0.55312263, 0.42484227, 0.95993503],
       [0.72169578, 0.97062797, 0.06894211],
       [0.70140959, 0.94653279, 0.42393828],
       [0.83454463, 0.57949155, 0.24690499]])

In [41]:
# Pseudo random numbers
#np.random.seed(seed=0)
random_array_4 = np.random.randint(5, size=(2,3))
random_array_4

array([[1, 4, 3],
       [2, 4, 1]])

In [42]:
random_array_4.shape , random_array_4.ndim , random_array_4.dtype , len(random_array_4) , random_array_4.size

((2, 3), 2, dtype('int32'), 2, 6)

In [43]:
#np.random.seed(seed=69)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.85768985, 0.692321  , 0.91981101],
       [0.71499818, 0.7126235 , 0.59979254],
       [0.01974049, 0.08820623, 0.3848037 ],
       [0.55469622, 0.59145195, 0.01908279],
       [0.4607805 , 0.8953545 , 0.53514637]])

# Viewing Arrays and Matrices

In [44]:
np.unique(random_array_4)

array([1, 2, 3, 4])

In [45]:
a1

array([1, 2, 3])

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
np.unique(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [49]:
a1[0]

1

In [50]:
a2[1]

array([5.6, 7. , 6.9])

In [54]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [55]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [56]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [67]:
a4 = np.random.randint(5.0 , size=(2,3,3,5),dtype=int)

In [68]:
a4

array([[[[4, 4, 4, 0, 3],
         [2, 1, 3, 0, 1],
         [0, 3, 4, 2, 1]],

        [[4, 0, 3, 3, 0],
         [4, 3, 1, 2, 3],
         [1, 1, 0, 3, 3]],

        [[4, 1, 2, 4, 3],
         [3, 3, 3, 0, 4],
         [4, 2, 4, 0, 4]]],


       [[[3, 4, 2, 4, 1],
         [0, 1, 0, 4, 4],
         [2, 3, 0, 2, 3]],

        [[4, 3, 1, 1, 2],
         [2, 1, 0, 3, 4],
         [1, 3, 0, 1, 0]],

        [[1, 2, 3, 2, 4],
         [2, 0, 4, 4, 0],
         [2, 1, 3, 4, 4]]]])

In [65]:
a4.shape,a4.ndim,a4.size,len(a4),type(a4)

((5, 3), 2, 15, 5, numpy.ndarray)

In [66]:
a4.sum()

35

In [71]:
# slice the 4 first elements in the array

a4[:,:,:,:1]

array([[[[4],
         [2],
         [0]],

        [[4],
         [4],
         [1]],

        [[4],
         [3],
         [4]]],


       [[[3],
         [0],
         [2]],

        [[4],
         [2],
         [1]],

        [[1],
         [2],
         [2]]]])

# Manipulating & Comparing Data

## Arithmetic 

In [72]:
a1

array([1, 2, 3])

In [77]:
ones = np.ones((5,3),dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [78]:
a1 + ones

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [81]:
a1 - ones

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [82]:
a1* ones

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [83]:
a1 * a2

array([[ 1.2, 10.6,  6. ],
       [ 5.6, 14. , 20.7]])

In [84]:
a1 / a2

array([[0.83333333, 0.37735849, 1.5       ],
       [0.17857143, 0.28571429, 0.43478261]])

In [86]:
np.dot(a2,a3)

array([[[ 36.4,  44.9,  53.4],
        [112.9, 121.4, 129.9]],

       [[ 81.9, 101.4, 120.9],
        [257.4, 276.9, 296.4]]])

ValueError: cannot reshape array of size 18 into shape (2,3)